//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/test_proto.proto
namespace proto.test_proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"proto_a")]
  public partial class proto_a : global::ProtoBuf.IExtensible
  {
    public proto_a() {}
    
    private readonly global::System.Collections.Generic.List<bool> _a = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(1, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> a
    {
      get { return _a; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _b = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> b
    {
      get { return _b; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _c = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(3, Name=@"c", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> c
    {
      get { return _c; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _d = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"d", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> d
    {
      get { return _d; }
    }
  
    private readonly global::System.Collections.Generic.List<proto_e> _e = new global::System.Collections.Generic.List<proto_e>();
    [global::ProtoBuf.ProtoMember(5, Name=@"e", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto_e> e
    {
      get { return _e; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"proto_e")]
  public partial class proto_e : global::ProtoBuf.IExtensible
  {
    public proto_e() {}
    
    private bool _a = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool a
    {
      get { return _a; }
      set { _a = value; }
    }
    private int _b = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int b
    {
      get { return _b; }
      set { _b = value; }
    }
    private float _c = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"c", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float c
    {
      get { return _c; }
      set { _c = value; }
    }
    private string _d = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"d", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string d
    {
      get { return _d; }
      set { _d = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}