// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Example
{
    public partial class ProtoA
    {
        public List<bool> A { get; set; }

        public List<int> B { get; set; }

        public List<float> C { get; set; }

        public List<string> D { get; set; }

        public List<Example.ProtoE> E { get; set; }

    }

    public partial class ProtoE
    {
        public bool A { get; set; }

        public int B { get; set; }

        public float C { get; set; }

        public string D { get; set; }

    }

}
